#!/bin/bash
#presence test

vert='\e[1;32m'
rouge='\e[0;31m' 
neutre='\e[0;m' 


testPackage=('yay' 'zsh' 'lsd' 'htop' 'youtube-dl' 'ffmpeg')
noPresent=()

echo -e "${vert}Presence test\n"

for package in ${testPackage[*]}
do
	if  pacman -Qs  $package > /dev/null
	then
		echo -e "${neutre}$ packer present"
	else 
		echo -e"${rouge}$ packer pas present"
		noPresent=( "${noPresent[@]}" $package)
	fi
done

if [ -z "$noPresent" ];then
	echo -e "\n${vert}no download"
else
    sudo pacman -S ${noPresent[*]}
fi



echo -e "${vert}Github"

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

git clone --depth=1 https://gitee.com/romkatv/powerlevel10k.git ~/powerlevel10k
echo 'source ~/powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc


echo -e "${vert}Config"

mkdir ~/.config/aliases
cp -r aliase.sh ~/.config/aliases/aliase.sh
echo "source ~/.config/aliases/aliase.sh" >> ~/.zshrc
echo -e "${vert}END"
